api_platform:
    title: 'OlimpoApp Api'
    version: '0.0.1'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/../almacenes/src/Warehouse/Warehouse/Domain'
            - '%kernel.project_dir%/../clientes/src/Customer/Customer/Domain'
            - '%kernel.project_dir%/../config/src/App/Account/Domain'
            - '%kernel.project_dir%/../config/src/App/Bank/Domain'
            - '%kernel.project_dir%/../config/src/App/Company/Domain'
            - '%kernel.project_dir%/../config/src/App/Dashboard/Domain'
            - '%kernel.project_dir%/../config/src/App/Irpf/Domain'
            - '%kernel.project_dir%/../config/src/App/Iva/Domain'
            - '%kernel.project_dir%/../config/src/App/Origin/Domain'
            - '%kernel.project_dir%/../config/src/App/PaymentMethod/Domain'
            - '%kernel.project_dir%/../config/src/App/Permission/Domain'
            - '%kernel.project_dir%/../config/src/App/Privacy/Domain'
            - '%kernel.project_dir%/../config/src/App/Rate/Domain'
            - '%kernel.project_dir%/../config/src/App/RealizationArea/Domain'
            - '%kernel.project_dir%/../config/src/App/System/Domain'
            - '%kernel.project_dir%/../dispositivos/src/Device/Device/Domain'
            - '%kernel.project_dir%/../documentos/src/Document/Invoice/Domain'
            - '%kernel.project_dir%/../grh/src/Grh/Dashboard/Domain'
            - '%kernel.project_dir%/../grh/src/Grh/Employee/Domain'
            - '%kernel.project_dir%/../grh/src/Grh/Event/Domain'
            - '%kernel.project_dir%/../grh/src/Grh/Fichar/Domain'
            - '%kernel.project_dir%/../grh/src/Grh/Report/Domain'
            - '%kernel.project_dir%/../productos/src/Product/Attribute/Domain'
            - '%kernel.project_dir%/../productos/src/Product/Option/Domain'
            - '%kernel.project_dir%/../productos/src/Product/Product/Domain'
