doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            CTICWarehouse:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../almacenes/src/Warehouse'
                prefix: 'CTIC\Warehouse'
                alias: CTICWarehouse
            CTICCustomer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../clientes/src/Customer'
                prefix: 'CTIC\Customer'
                alias: CTICCustomer
            CTICApp:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../config/src/App'
                prefix: 'CTIC\App'
                alias: CTICApp
            CTICDevice:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../dispositivos/src/Device'
                prefix: 'CTIC\Device'
                alias: CTICDevice
            CTICDocument:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../documentos/src/Document'
                prefix: 'CTIC\Document'
                alias: CTICDocument
            CTICGrh:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../grh/src/Grh'
                prefix: 'CTIC\Grh'
                alias: CTICGrh
            CTICProduct:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../productos/src/Product'
                prefix: 'CTIC\Product'
                alias: CTICProduct
