#index:
#    path: /
#    controller: App\Controller\DefaultController::index


register:
  path: /register
  controller: App\Controller\ApiController::register
  methods: POST

api_checker:
  path: /api_check
  controller: App\Controller\ApiController::api

login_check:
  path: /login
  methods: ['POST']